name: Publish Templates

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/publish.yaml"
      - "src/**"
      - "test/**"

permissions:
  packages: write
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Publish Templates
        uses: devcontainers/action@v1
        with:
          publish-templates: false
          base-path-to-templates: ./src
          generate-docs: true

      - name: Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          title: "chore: update documentation"
          commit-message: "chore: update documentation"
          add-paths: |
            **/README.md
