name: Push Devcontainer Images

on:
  schedule:
    - cron: "0 18 * * *" # Daily at 1800 UTC
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        template:
          - base
          - dev-common
          - devpod
          - devcontainers
          - picolayer
    steps:
      - uses: actions/checkout@v6

      # TODO: Templates that use options (e.g., the 'hello' template) fail because this action
      # does not support passing options to the build. Alternative solutions are
      # to create an action that builds images using the template defaults or a build-spec.json
      # file in each template directory to configure the images that need to be built.
      #
      # For now, these templates need to be built manually and pushed to the container registry.

      - name: Push image for '${{ matrix.template }}'
        uses: ./.github/actions/push-image
        with:
          template: "${{ matrix.template }}"
          token: "${{ secrets.GITHUB_TOKEN }}"
